version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: store_front_api_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: store_front_api_app_dev
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  # Production service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: store_front_api_app
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      TEST_DB_NAME: ${TEST_DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      BCRYPT_PASSWORD: ${BCRYPT_PASSWORD}
      SALT_ROUNDS: ${SALT_ROUNDS}

  # Test service
  app-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    container_name: store_front_api_app_test
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${TEST_DB_NAME}
    command: sh -c "npm run migrate:test && npm run test"

volumes:
  postgres_data:

